In [30]:
import pandas as pd
import numpy as np

In [31]:
Data = {
    "Name": ["Alex","Bob","Charlie","David","Eve","Alex"],
    "Age" : [25,30,35,np.nan,29,25],
    "Department" : ["HR","IT","Finance","IT","HR","HR"],
    "Salary" : [50000,60000,70000,62000,np.nan,50000],
    "Promoted_Salary" : [52000,62000,72000,64000,np.nan,52000]
}

In [32]:
df = pd.DataFrame(Data)
df

      Name   Age Department   Salary  Promoted_Salary
0     Alex  25.0         HR  50000.0          52000.0
1      Bob  30.0         IT  60000.0          62000.0
2  Charlie  35.0    Finance  70000.0          72000.0
3    David   NaN         IT  62000.0          64000.0
4      Eve  29.0         HR      NaN              NaN
5     Alex  25.0         HR  50000.0          52000.0

In [18]:
#Checking how many nulls values there are in the dataframe:
df.isnull().sum()
#The data represents how many null values each column has.

Name               0
Age                1
Department         0
Salary             1
Promoted_Salary    1
dtype: int64

In [19]:
#To drop rows containing null values:
print(df.dropna())

print("\n------------------------------------------------------------------\n")
#To drop the row only if all the data in the row is null:
print(df.dropna(how = "all"),)
print("\n------------------------------------------------------------------\n")

      Name   Age Department   Salary  Promoted_Salary
0     Alex  25.0         HR  50000.0          52000.0
1      Bob  30.0         IT  60000.0          62000.0
2  Charlie  35.0    Finance  70000.0          72000.0
5     Alex  25.0         HR  50000.0          52000.0

------------------------------------------------------------------

      Name   Age Department   Salary  Promoted_Salary
0     Alex  25.0         HR  50000.0          52000.0
1      Bob  30.0         IT  60000.0          62000.0
2  Charlie  35.0    Finance  70000.0          72000.0
3    David   NaN         IT  62000.0          64000.0
4      Eve  29.0         HR      NaN              NaN
5     Alex  25.0         HR  50000.0          52000.0

------------------------------------------------------------------

Removing null values by filling them using fillna method:

In [20]:
#Filling with zero:
df.fillna(0)
print(df)

      Name   Age Department   Salary  Promoted_Salary
0     Alex  25.0         HR  50000.0          52000.0
1      Bob  30.0         IT  60000.0          62000.0
2  Charlie  35.0    Finance  70000.0          72000.0
3    David   NaN         IT  62000.0          64000.0
4      Eve  29.0         HR      NaN              NaN
5     Alex  25.0         HR  50000.0          52000.0

In [21]:
#Filling the null values with the mean of those columns:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [22]:
#Filling the null value with median:
df["Salary"].fillna(df["Salary"].median())

0    50000.0
1    60000.0
2    70000.0
3    62000.0
4    60000.0
5    50000.0
Name: Salary, dtype: float64

There are two different methods of filling null values without specifying data
FowardFill"ffill" and BackwardFill "bfill"
FowardFill Fills the null value with the last value encountered,
Reverse for the Backward fill

In [23]:
#Chanig the values in the clumns:
df["Name"] = df["Name"].replace("Charlie", "Rose")

In [24]:
df

    Name   Age Department   Salary  Promoted_Salary
0   Alex  25.0         HR  50000.0          52000.0
1    Bob  30.0         IT  60000.0          62000.0
2   Rose  35.0    Finance  70000.0          72000.0
3  David   NaN         IT  62000.0          64000.0
4    Eve  29.0         HR      NaN              NaN
5   Alex  25.0         HR  50000.0          52000.0

REMOVING THE DUPLICATE ELEMENTS:

In [25]:
#Finding the duplicates:
df_dup = df[df.duplicated(keep = "first")]
df_dup

   Name   Age Department   Salary  Promoted_Salary
5  Alex  25.0         HR  50000.0          52000.0

In [26]:
#To drop the duplicate value
df = df.drop_duplicates()
df

    Name   Age Department   Salary  Promoted_Salary
0   Alex  25.0         HR  50000.0          52000.0
1    Bob  30.0         IT  60000.0          62000.0
2   Rose  35.0    Finance  70000.0          72000.0
3  David   NaN         IT  62000.0          64000.0
4    Eve  29.0         HR      NaN              NaN

In [27]:
#apply and lambda helps change single entries based on certain conditions.
# def multiply_age(x):
#     return x*2
# df["Age"] = df["Age"].apply()
df["Age"] = df["Age"].apply(lambda x: x/2)
df

C:\Users\Gupta\AppData\Local\Temp\ipykernel_21236\1442386562.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(lambda x: x/2)

    Name   Age Department   Salary  Promoted_Salary
0   Alex  12.5         HR  50000.0          52000.0
1    Bob  15.0         IT  60000.0          62000.0
2   Rose  17.5    Finance  70000.0          72000.0
3  David   NaN         IT  62000.0          64000.0
4    Eve  14.5         HR      NaN              NaN

JOIN AND MERGE:

In [34]:
department_info = {
    "Department" : ["HR", "IT", "Finance"],
    "Location" : ["New York", "San Francisco", "Chicago"],
    "Manager" : ["Laura", "Steve", "Nina"]
}
df2 = pd.DataFrame(department_info)
df2

  Department       Location Manager
0         HR       New York   Laura
1         IT  San Francisco   Steve
2    Finance        Chicago    Nina

In [38]:
#Concat: Horizontal stacking
pd.concat([df,df2])

      Name   Age Department   Salary  Promoted_Salary       Location Manager
0     Alex  25.0         HR  50000.0          52000.0            NaN     NaN
1      Bob  30.0         IT  60000.0          62000.0            NaN     NaN
2  Charlie  35.0    Finance  70000.0          72000.0            NaN     NaN
3    David   NaN         IT  62000.0          64000.0            NaN     NaN
4      Eve  29.0         HR      NaN              NaN            NaN     NaN
5     Alex  25.0         HR  50000.0          52000.0            NaN     NaN
0      NaN   NaN         HR      NaN              NaN       New York   Laura
1      NaN   NaN         IT      NaN              NaN  San Francisco   Steve
2      NaN   NaN    Finance      NaN              NaN        Chicago    Nina

In [39]:
#Concat based on department:
pd.concat([df,df2], axis = 1)

,Name,Age,Department,Salary,Promoted_Salary,Department,Location,Manager
0,Alex,25.0,HR,50000.0,52000.0,HR,New York,Laura
1,Bob,30.0,IT,60000.0,62000.0,IT,San Francisco,Steve
2,Charlie,35.0,Finance,70000.0,72000.0,Finance,Chicago,Nina
3,David,NaN,IT,62000.0,64000.0,NaN,NaN,NaN
4,Eve,29.0,HR,NaN,NaN,NaN,NaN,NaN
5,Alex,25.0,HR,50000.0,52000.0,NaN,NaN,NaN

In [42]:
#Merging withgout repreating columns:
pd.merge(df,df2, on = "Department")

      Name   Age Department   Salary  Promoted_Salary       Location Manager
0     Alex  25.0         HR  50000.0          52000.0       New York   Laura
1      Bob  30.0         IT  60000.0          62000.0  San Francisco   Steve
2  Charlie  35.0    Finance  70000.0          72000.0        Chicago    Nina
3    David   NaN         IT  62000.0          64000.0  San Francisco   Steve
4      Eve  29.0         HR      NaN              NaN       New York   Laura
5     Alex  25.0         HR  50000.0          52000.0       New York   Laura