In [6]:
import pandas as pd
import numpy as np

In [9]:
Data = {
    "Name": ["Alex","Bob","Charlie","David","Eve","Alex"],
    "Age" : [25,30,35,np.nan,29,25],
    "Department" : ["HR","IT","Finance","IT","HR","HR"],
    "Salary" : [50000,60000,70000,62000,np.nan,50000]
}

In [10]:
Data

{'Name': ['Alex', 'Bob', 'Charlie', 'David', 'Eve', 'Alex'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [14]:
#Converting the above data into DataFrame:
df = pd.DataFrame(Data)
df

      Name   Age Department   Salary
0     Alex  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5     Alex  25.0         HR  50000.0

In [18]:
#To see only the first two rows:
print(df.head(2))
print("-----------------------------------------------------\n")

#To see the last two values:
print(df.tail(2))

   Name   Age Department   Salary
0  Alex  25.0         HR  50000.0
1   Bob  30.0         IT  60000.0
-----------------------------------------------------

   Name   Age Department   Salary
4   Eve  29.0         HR      NaN
5  Alex  25.0         HR  50000.0

In [19]:
#Using iloc with df
df.iloc[1:3] #iloc[Starting row : Ending Row(Not included), :Columns to included(All by default)]

      Name   Age Department   Salary
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0

In [21]:
#Filetering using loc with departments:
df.loc[1:3, ["Name","Age","Department"]]#loc[Starting row : Ending Row, :Columns to included(All by default,Using column name)]

      Name   Age Department
1      Bob  30.0         IT
2  Charlie  35.0    Finance
3    David   NaN         IT

In [25]:
#Droping a column:
df.drop("Age", axis = 1)#axi =1 drops the entire column
#The column age is not deleted rather it is hidden for this output
#To make the changes permanent we use the keyword "inplace = True"

      Name Department   Salary
0     Alex         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5     Alex         HR  50000.0

In [31]:
#To check Info of dataFrame:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes
None

In [32]:
#To get statistical Information about the dataset we use the describe function
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

In [33]:
#DataFrames also support broadcasting:
df["Salary"] = df["Salary"] + 5000
df

      Name   Age Department   Salary
0     Alex  25.0         HR  55000.0
1      Bob  30.0         IT  65000.0
2  Charlie  35.0    Finance  75000.0
3    David   NaN         IT  67000.0
4      Eve  29.0         HR      NaN
5     Alex  25.0         HR  55000.0

In [47]:
#Renaming columns:
df.rename(columns = {"Department" : "Dept"}, inplace = True)

In [51]:
#To find the number of unique elements in a column:
print(df["dept"].unique())

#To find the frequency of each unique elements:
print(df["dept"].value_counts())

['HR' 'IT' 'Finance']
dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64